FROM public.ecr.aws/lambda/python:3.12

# Update DNF and install OpenJDK 11
RUN dnf install -y tar gzip \
    && curl -sL https://rpm.nodesource.com/setup_16.x | bash - \
    && dnf install -y nodejs \dnf install -y java-11-amazon-corretto-devel \ 
    && dnf install -y dotnet-sdk-6.0 \
    && dotnet tool install -g dotnet-script 

# Copy requirements.txt
COPY requirements.txt ${LAMBDA_TASK_ROOT}

# Install the specified packages
RUN pip install -r requirements.txt

# Copy function code
COPY lambda_function.py ${LAMBDA_TASK_ROOT}

# Set the CMD to your handler
CMD [ "lambda_function.handler" ]